import Course1 from "./images/course1.jpg";
import Course2 from "./images/course2.jpg";
import Course3 from "./images/sector3.jpg";
import Course4 from "./images/course4.jpg";

const courseData = [
  {
    id: 1,
    image: Course1,
    title: "The Complete 2022 Web Development Bootcamp",
    authorFristName: "Jhon",
    authorLastName: "Doe",
    rating: 5,
    price: "$225",
  },
  {
    id: 2,
    image: Course2,
    title: `Javascript Complete guide for beginners`,
    authorFristName: "Jhon",
    authorLastName: "Doe",
    rating: 5,
    price: "$100",
  },
  {
    id: 3,
    image: Course3,
    title: "The Complete artificial intelligence course",
    authorFristName: "Jhon",
    authorLastName: "Doe",
    rating: 5,
    price: "$25",
  },
  {
    id: 4,
    image: Course4,
    title: "The Complete 2022 Web Development Bootcamp",
    authorFristName: "Jhon",
    authorLastName: "Doe",
    rating: 5,
    price: "$220",
  },
  {
    id: 5,
    image: Course4,
    title: "The Complete 2022 Web Development Bootcamp",
    authorFristName: "Jhon",
    authorLastName: "Doe",
    rating: 5,
    price: "$220",
  },
  {
    id: 6,
    image: Course3,
    title: "The Complete 2022 Web Development Bootcamp",
    authorFristName: "Jhon",
    authorLastName: "Doe",
    rating: 5,
    price: "$220",
  },
  {
    id: 7,
    image: Course2,
    title: "The Complete 2022 Web Development Bootcamp",
    authorFristName: "Jhon",
    authorLastName: "Doe",
    rating: 5,
    price: "$220",
  },
  {
    id: 8,
    image: Course1,
    title: "The Complete 2022 Web Development Bootcamp",
    authorFristName: "Jhon",
    authorLastName: "Doe",
    rating: 5,
    price: "$220",
  },
  {
    id: 9,
    image: Course1,
    title: "The Complete 2022 Web Development Bootcamp",
    authorFristName: "Jhon",
    authorLastName: "Doe",
    rating: 5,
    price: "$225",
  },
  {
    id: 10,
    image: Course2,
    title: `Javascript Complete guide for beginners`,
    authorFristName: "Jhon",
    authorLastName: "Doe",
    rating: 5,
    price: "$100",
  },
  {
    id: 11,
    image: Course3,
    title: "The Complete artificial intelligence course",
    authorFristName: "Jhon",
    authorLastName: "Doe",
    rating: 5,
    price: "$25",
  },
  {
    id: 12,
    image: Course4,
    title: "The Complete 2022 Web Development Bootcamp",
    authorFristName: "Jhon",
    authorLastName: "Doe",
    rating: 5,
    price: "$220",
  },
];

export default courseData;
